private: true
type: module
scripts:
  postinstall: node @internal/scripts/loader/repo-post-install.js
  pretty: biome check --diagnostic-level=warn --unsafe
  build: node @mpis/monorepo/loader/bin.devel.js build
  watch: node @mpis/monorepo/loader/bin.devel.js watch
  publish-everything: node @build-script/package-tools/load.js monorepo-publish --concurrency 1
  package-tools: node @build-script/package-tools/load.js
  link: node @build-script/package-tools/load.js monorepo-link-binaries --recursive
  check: node @internal/scripts/loader/repo-check-all.js
  clean: node @internal/scripts/loader/repo-clean.js
  remote-publish: node @internal/scripts/loader/remote-publish.js
devDependencies:
  '@biomejs/biome': ^2.4.8
  execa: ^9.6.1
  typescript: ^5.9.3
  browserslist: ^4.28.1

packageManager: pnpm@10.28.0
