packages:
  - .
  - .opencode/tools
  - '@mpis/*'
  - '@build-script/*'
  - '@gongt/*'
  - '@gongt/*/example'
  - '@gongt/*/examples/*'
  - '@idlebox/*'
  - '@idlebox/itypes/subpackages/*'
  - '@internal/*'
  - standalone/*

# patchedDependencies:
# "@types/tar-stream": "patches/@types__tar-stream.patch"

enablePrePostScripts: true
fetchRetries: 1000
gitChecks: false

hoist: false
hoistPattern:
  - ""
publicHoistPattern:
  - "@types/*"
  - "@biomejs/biome"
  - "source-map-support"
  - "@idlebox/native-executer"
hoistWorkspacePackages: false
ignoreWorkspaceCycles: true

ignoredOptionalDependencies:
  - fsevents
networkConcurrency: 3
nodeOptions: "${NODE_OPTIONS:- } --enable-source-maps"

unsafePerm: true
# 一般状况下，pnpm run xxxx 会检查是否有依赖修改，需要的话自动运行 pnpm install
# 但由于检查修改过程中本来就会改动package.json文件，所以此项在workflow中被替换为“false”
# 用于sed修改
verifyDepsBeforeRun: false

allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  '@swc/core': true

overrides:
  ajv: '^8.17.1'
packageExtensions:
  "@rushstack/heft-typescript-plugin":
    dependencies:
      "typescript": "<7"

patchedDependencies:
  amaro: patches/amaro.patch

# 使用国内镜像源以加快依赖下载速度，workflow中会根据需要替换为官方源
registry: https://registry.npmmirror.com
savePrefix: '^'

saveWorkspaceProtocol: rolling

autoInstallPeers: false
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: false

minimumReleaseAgeExclude:
  - knip@6.32.0
