packages:
  - .
  - '@mpis/*'
  - '@build-script/*'
  - '@gongt/*'
  - '@idlebox/*'
  - '@internal/*'
  - standalone/*

enablePrePostScripts: true
hoistWorkspacePackages: false

ignoredOptionalDependencies:
  - fsevents
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - '@swc/core'

# autoInstallPeers: false
strictPeerDependencies: true

hoist: false
publicHoistPattern:
  - "@types/*"
  - "@biomejs/biome"
  - "source-map-support"
hoistPattern:
  - ""

overrides:
  ajv: '^8.17.1'

saveWorkspaceProtocol: rolling
savePrefix: '^'
ignoreWorkspaceCycles: true
nodeOptions: ''

patchedDependencies:
  "@types/tar-stream": "patches/@types__tar-stream.patch"

# npm config
access: public
alwaysAuth: false
fetchRetries: 1000
networkConcurrency: 3
gitChecks: false

publishConfig:
  preferOffline: false
  preferFrozenLockfile: false
  gitChecks: false
