packages:
  - .
  - '@mpis/*'
  - '@build-script/*'
  - '@gongt/*'
  - '@idlebox/*'
  - '@internal/*'
  - standalone/*

enablePrePostScripts: true
hoistWorkspacePackages: false

ignoredOptionalDependencies:
  - fsevents
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild

autoInstallPeers: false
nodeOptions: ''

hoist: false
publicHoistPattern:
  - "@types/*"
  - "@biomejs/biome"
  - "source-map-support"
hoistPattern:
  - ""

overrides:
  ajv: '^8.17.1'

saveWorkspaceProtocol: rolling
savePrefix: '^'
ignoreWorkspaceCycles: true


patchedDependencies:
  "@types/tar-stream": "patches/@types__tar-stream.patch"
