import { readFileIfExists, writeFileIfChange } from '@idlebox/node';
import { lstat, unlink, writeFile } from 'node:fs/promises';
import pkg from '../../package.json' with { type: 'json' };

export const safeGuard = '7ee549c4-560a-44f6-83a7-372cce8a4508';
export const safeGuardComment = `# Wrapper script generated by ${pkg.name}@${pkg.version}
# DO NOT EDIT THIS FILE | ${safeGuard}`;
export const safeGuardCommentBat = `REM Wrapper script generated by ${pkg.name}@${pkg.version}
REM DO NOT EDIT THIS FILE | ${safeGuard}`;

export async function defaultWriteFile(file: string, content: string): Promise<boolean> {
	let ss = await lstat(file).catch(() => null);
	if (ss?.isSymbolicLink()) {
		await unlink(file);
		ss = null;
	}

	let ch = true;
	if (ss) {
		ch = await writeFileIfChange(file, content);
	} else {
		await writeFile(file, content);
	}
	return ch;
}

export async function writeInteractive(file: string, content: string): Promise<boolean> {
	let ss = await lstat(file).catch(() => null);
	if (ss) {
		const original = await readFileIfExists(file, 'utf-8');
		if (original === content) return false;

		if (!original.includes(safeGuard)) {
			await askOverride(file);
		}

		if (ss.isSymbolicLink()) {
			// 防止符号链接导致非预期行为。删除它，假装之前stat不存在。
			await unlink(file);
			ss = null;
		}
	}

	// 如果文件已存在，则已经判断过内容相同，不需要再次检查。
	await writeFile(file, content);
	return true;
}

async function askOverride(file: string): Promise<void> {
	if (!process.stdin.isTTY) {
		throw new Error(`文件 ${file} 已存在，拒绝覆盖。`);
	}

	const response = await new Promise<string>((resolve) => {
		process.stdout.write(`文件 ${file} 已存在. 是否覆盖? (y/N): `);
		process.stdin.once('data', (data) => resolve(data.toString().trim()));
	});
	if (response.toLowerCase() !== 'y' && response !== '是') {
		throw new Error(`不覆盖文件: ${file}`);
	}
}
