import pkg from '../../package.json' with { type: 'json' };

export const safeGuard = '7ee549c4-560a-44f6-83a7-372cce8a4508';
export const safeGuardComment = `# Wrapper script generated by ${pkg.name}@${pkg.version}
# DO NOT EDIT THIS FILE | ${safeGuard}`;
export const safeGuardCommentBat = `REM Wrapper script generated by ${pkg.name}@${pkg.version}
REM DO NOT EDIT THIS FILE | ${safeGuard}`;
