// DO NOT EDIT THIS FILE
// @ts-ignore
/* eslint-disable */

/* common/exec.ts */
	// Identifiers
/* common/find-root.ts */
	// Identifiers
	export { findMonorepoRoot } from "./common/find-root.js";
	export { findMonorepoRootSync } from "./common/find-root.js";
/* common/import-package-json.ts */
	// Identifiers
	export { importPackageJson } from "./common/import-package-json.js";
/* common/strings.ts */
	// Identifiers
	export { normalizePackageName } from "./common/strings.js";
/* workspace/common/types.ts */
	// Identifiers
	export { PackageManagerKind } from "./workspace/common/types.js";
	export { WorkspaceKind } from "./workspace/common/types.js";
	export type { IPackageInfo } from "./workspace/common/types.js";
	export type { IPackageInfoRW } from "./workspace/common/types.js";
/* workspace/common/deduplicate-dependency.ts */
	// Identifiers
/* workspace/drivers/lerna-nx.ts */
	// Identifiers
	export { lernaListProjects } from "./workspace/drivers/lerna-nx.js";
	export { nxListProjects } from "./workspace/drivers/lerna-nx.js";
/* workspace/drivers/npm.ts */
	// Identifiers
	export { npmListProjects } from "./workspace/drivers/npm.js";
/* workspace/drivers/pnpm.ts */
	// Identifiers
	export { pnpmListProjects } from "./workspace/drivers/pnpm.js";
/* workspace/drivers/rush.ts */
	// Identifiers
	export { rushListProjects } from "./workspace/drivers/rush.js";
/* workspace/drivers/yarn.ts */
	// Identifiers
	export { yarnListProjects } from "./workspace/drivers/yarn.js";
/* workspace/index.ts */
	// Identifiers
	export { WorkspaceBase } from "./workspace/index.js";
	export { MonorepoWorkspace } from "./workspace/index.js";
	export { SimplePackage } from "./workspace/index.js";
	export type { IDecoupleMethod } from "./workspace/index.js";
/* workspace/common/create.ts */
	// Identifiers
	export { NotMonorepo } from "./workspace/common/create.js";
	export { createWorkspaceOrPackage } from "./workspace/common/create.js";
	export { createSimpleProject } from "./workspace/common/create.js";
	export { createWorkspace } from "./workspace/common/create.js";