name: publish to npm
on:
  push:
    branches:
      - release
env:
  NODE_ENV: production
  DISABLE_SYSTEMD: yes
  NEVER_UNSHARE: yes
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@5cdc17f4f91a30861d1f7be16f34719371d804d7
        env:
          DELETE: 'yes'
          GITHUB_TOKEN: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    name: 'Publish with rush'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          clean: true
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-gongt-baobao
          restore-keys: |
            pnpm
      - name: 'Install'
        run: node common/scripts/install-run-rush.js install
      - name: 'Build'
        run: node common/scripts/install-run-rush.js rebuild
      - name: 'Publish'
        run: node common/scripts/install-run-rush.js ypublish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
