name: 发布新版本
run-name: ${{ github.actor }} 提交了一个新的节点版本 🚀

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      skip_check:
        description: 跳过“检测修改并提交”步骤
        required: false
        type: boolean
        default: false

jobs:
  cache:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v6
        with:
          clean: true

      - name: 安装pnpm
        uses: pnpm/action-setup@master
        with:
          standalone: true
          cache: true
          package_json_file: package.yaml

      - name: 安装依赖
        run: |
          bash .github/scripts/post-pnpm-install.sh

          pnpm install --frozen-lockfile
          pnpm store prune --force

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    needs: cache
    # env:
    #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: 安装pnpm
        uses: pnpm/action-setup@master
        with:
          standalone: true
          cache: true
          package_json_file: package.yaml

      - name: 安装依赖
        run: |
          bash .github/scripts/post-pnpm-install.sh

          pnpm install --frozen-lockfile
          pnpm store prune --force

      - name: 执行构建
        run: |
          npm config --location=user set cache="${RUNNER_TEMP}/npm"
          pnpm run build

      - name: 检测修改并提交
        # if: "!inputs.skip_check"
        run: source .github/scripts/check-commit.sh

      # - name: 跳过检测打包
      #   if: "inputs.skip_check"
      #   run: pnpm run ???

      - name: 发布新版本
        run: node --experimental-strip-types .github/scripts/publish-all-tarball.ts
