name: Test Build
on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Rebuild without cache (default false)'
        required: false
        default: false
  push:
    branches:
      - master
env:
  NODE_ENV: production
  NEVER_UNSHARE: yes
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@v1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DELETE: 'yes'
  build:
    runs-on: ubuntu-latest
    name: 'Run build with rush'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          clean: false
          fetch-depth: 0
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm
      - name: 'Install'
        run: node common/scripts/install-run-rush.js update
      - name: 'Build'
        if: '!${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js build
      - name: 'Rebuild'
        if: '${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js rebuild
