name: Test Build
on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Rebuild without cache (default false)'
        required: false
        default: false
  push:
    branches:
      - master
env:
  NODE_ENV: production
  http_proxy: http://proxy-server.:3271
  DISABLE_SYSTEMD: yes
jobs:
  build:
    runs-on: [self-hosted, linux]
    name: 'Run build with rush'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          clean: false
          fetch-depth: 0
      - name: 'Install'
        run: node common/scripts/install-run-rush.js install
      - name: 'Build'
        if: '!${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js build
      - name: 'Rebuild'
        if: '${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js rebuild
