name: Test Build
on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'rush rebuild insteadof build (default yes)'
        required: false
        default: true
  push:
    branches:
      - master
env:
  NODE_ENV: development
  NEVER_UNSHARE: yes
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@6dd7af8389c9434cc893fd33b58609e73db49fbe
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DELETE: 'yes'
  build:
    runs-on: ubuntu-latest
    name: 'Run build with rush'
    steps:
      - name: '签出代码'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          clean: false
          fetch-depth: 0

      - name: 'npm下载缓存'
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            common-

      - name: '安装npm依赖'
        run: node common/scripts/install-run-rush.js update

      - name: '运行构建（带缓存）'
        if: '!${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js build

      - name: '运行全部构建过程'
        if: '${{ github.event.inputs.rebuild }}'
        run: node common/scripts/install-run-rush.js rebuild

      - name: '检查构建状态'
        run: |
          git add .
          if [[ "$(git status --porcelain)" ]]; then
            git diff --cached >&2
            echo "::error ::构建后有文件发生变化" >&2
          fi

      - name: '发布版本号有变化的包到NPM'
        run: |
          node common/scripts/install-run-rush.js build-autoinstaller
          node common/scripts/install-run-rush.js ypublish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
